services:
#    bremen_hack_insight.example:
#        class: BremenHack\InsightBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]



parameters:
  datasets:
    "17397":
      name: Vorausschätzung: Durchschnittsalter nach Geschlecht 2030 in Bremen
      filename: 17397.csv
      csv: http://www.statistik-bremen.de/soev/abfrage_csv.cfm?tabelle=17397
      info: http://transparenz.bremen.de/sixcms/detail.php?gsid=bremen65.c.17283.de&asl=bremen02.c.734.de
      controlColumn: 3
      labelRow: 2


    "17355":
      name: Bevölkerung nach Migrationsstatus, Geschlecht und Altersgruppen
      filename: 17355.csv
      csv: http://www.statistik-bremen.de/soev/abfrage_csv.cfm?tabelle=17355
      info: http://transparenz.bremen.de/sixcms/detail.php?gsid=bremen65.c.17184.de&asl=bremen02.c.734.de
      controlColumn: 3
      labelRow: 2


    "17322":
      name: Durchschnittliches Alter der Bevölkerung Bremen
      filename: 17322.csv
      csv: http://www.statistik-bremen.de/soev/abfrage_csv.cfm?tabelle=17322
      info:   http://transparenz.bremen.de/sixcms/detail.php?gsid=bremen65.c.17224.de&asl=bremen02.c.734.de
      controlColumn: 2
      labelRow: 3


  bremenMapping:
    "4#Bremen":
        "4011#Stadt Bremen":
            "40111#Mitte Bezirk":
                "401111#Mitte Stadteil":
                    - 4011111#Altstadt
                    - 4011112#Bahnhofsvorstadt
                    - 4011113#Ostertor
                "401112#Haefen":
                    - 4011121#Handelshaefen
                    - 4011122#Industriehaefen
                    - 4011123#Stadtbr Ueberseehafengebiet Bremerhaven
                    - 4011124#Neustaedter Hafen
                    - 4011125#Hohentorshafen
            "40112#Sued":
                "401121#Neustadt":
                    - 4011211#Alte Neustadt
                    - 4011212#Hohentor
                    - 4011213#Neustadt
                    - 4011214#Suedvorstadt
                    - 4011215#Gartenstadt Sued
                    - 4011216#Buntentor
                    - 4011217#Neuenland
                    - 4011218#Huckelriede
                "401123#Obervieland":
                    - 4011231#Habenhausen
                    - 4011232#Arsten
                    - 4011233#Kattenturm
                    - 4011234#Kattenesch
                "401124#Huchtingen":
                    - 4011241#Mittelshuchtingen
                    - 4011242#Sodenmatt
                    - 4011243#Kirchhuchtingen
                    - 4011244#Grolland
                "401125#Woltmershausen":
                    - 4011251#Woltmershausen
                    - 4011252#Rablinghausen
                "4011261#Seehausen":
                    - 4011261#Seehausen
                "4011271#Strom":
                    - 4011271#Strom
            "40113#Ost":
                "401131#Oestliche Vorstadt":
                    - 4011311#Steintor
                    - 4011312#Fesenfeld
                    - 4011313#Peterswerder
                    - 4011314#Hulsberg
                "401132#Schwachhausen":
                    - 4011321#Neu Schwachhausen
                    - 4011322#Buergerpark
                    - 4011323#Barkhof
                    - 4011324#Riensberg
                    - 4011325#Radio Bremen
                    - 4011326#Schwachhausen
                    - 4011327#Gete
                "401133#Vahr":
                    - 4011331#Gartenstadt Vahr
                    - 4011332#Neue Vahr Nord
                    - 4011333#Neue Vahr Suedwest
                    - 4011334#Neue Vahr Suedost



